### ISSUE TITLE
Adding matched-data-cli option to accept input file 

### ISSUE THREAD

**Issue by aprudhomme321** [cloudflare/matched-data-cli#12]
Hi, 

the tool is really helpful. However I'm facing an issue because many of my payload string are over the maximum size linux argument authorized. Indeed max size for a single argument is defined as "MAX_ARG_STRLEN = 32* PAGE_SIZE" while PAGE_FILE = 4KB (for 95% of time). Therefore max size or a single argument can not exceed 128KB

We have regularly payload size to decrypt over150KB and therefore execution failed with error 

 ./matched-data-cli: Argument list too long

Would it be possible to add an option "decryptfile" on matched-data-cli so that tool can accept file as imput ?

Many thanks by advance 

Regards

**Comment by migueldemoura** [comment]
Hi @aprudhomme321, this has been addressed with the release of [v0.5.0](https://github.com/cloudflare/matched-data-cli/releases/tag/v0.5.0). Thanks!
